#!/bin/sh

set -e

export REPO_URL="https://$GH_TOKEN@github.com/$GH_REPO.git"
git config --global user.email "$GIT_EMAIL"
git config --global user.name "$GIT_NAME"
git remote rename origin old
git remote -v
git remote add origin $REPO_URL
git config remote.origin.url $REPO_URL

node_modules/.bin/docpad deploy-ghpages --env static
